name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'  # Use 'adopt' for Adoptium/AdoptOpenJDK
          cache: 'maven'  # Cache Maven dependencies (optional)

      - name: Build with Maven
        run: mvn clean package

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to Elastic Beanstalk
        run: |
          # Install Elastic Beanstalk CLI
          pip install awsebcli

          # Initialize Elastic Beanstalk
          eb init -p java-17 ${{ secrets.EB_APP_NAME }} --region ${{ secrets.AWS_REGION }}

          # Create or update the Elastic Beanstalk environment
          eb deploy --staged
