name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'adopt-openjdk'

    - name: Build with Maven
      run: mvn package

    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp target/mywebsite-0.0.1-SNAPSHOT.jar deploy/app.jar
        cd deploy
        zip -r ../app.zip .

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        application_name: 'webapp'
        environment_name: 'website'
        version_label: ${{ github.run_id }}
        region: 'ap-south-1'
        bucket_name: 'elasticbeanstalk-ap-south-1-122238031788'
        bucket_key: 'app.zip'
        deploy_package: 'app.zip'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
