name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Commit ID to deploy'
        required: true
        default: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Save JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-app-jar
          path: target/mywebsite-0.0.1-SNAPSHOT.jar

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.commit_id != '' }}

    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: my-app-jar

      - name: List files in target directory
        run: ls -l target/

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v15
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}  
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ env.TAG_NAME }} 
          deployment_package: target/mywebsite-0.0.1-SNAPSHOT.jar
          use_existing_version_if_available: true


























# name: Deploy to Elastic Beanstalk

# on:
#   push:
#     branches:
#       - dev
#   create:
#     tags:
#       - 'R-*'

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.ref == 'refs/heads/dev'
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up JDK 21
#         uses: actions/setup-java@v3
#         with:
#           distribution: 'corretto'
#           java-version: '21'

#       - name: Build with Maven
#         run: mvn clean install

#       - name: Save JAR artifact
#         uses: actions/upload-artifact@v3
#         with:
#           name: my-app-jar
#           path: target/mywebsite-0.0.1-SNAPSHOT.jar

  