name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }} # Ensures that the latest commit is checked out

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: eb-artifact
          path: target/*.jar

  deploy_prod:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/dev' }}

    steps:
      - name: Download latest artifact from GitHub
        uses: actions/download-artifact@v3
        with:
          name: eb-artifact
          path: target/

      - name: List files in target directory
        run: ls -l target/

      - name: Get latest artifact name
        id: get_latest_artifact
        run: |
          latest_file=$(ls -t target/*.jar | head -n1)
          echo "LATEST_ARTIFACT=$latest_file" >> $GITHUB_ENV

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v15
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: ${{ env.LATEST_ARTIFACT }}
          use_existing_version_if_available: true
